### ISSUE TITLE
make asset range repeating methodology more flexible

### ISSUE THREAD

**Issue by hburgund** [hburgund/roundware-server#158]
Current methodology:

* listener enters range of asset
* asset becomes part of ```nearby_unplayed_recordings``` list
* asset eventually plays and gets moved to ```nearby_played_recordings``` list
* listener leaves range of asset and asset is added to ```far_recordings``` list
* listener re-enters asset's range and is added back to ```nearby_unplayed_recordings``` list, making it available to be played again in the stream

If a listener is standing near the edge of a range of an asset, GPS jumpiness or small motions can cause the asset to be played again in quick succession per the above methodology.

Proposed methodology:

* listener enters range of asset
* asset becomes part of ```nearby_unplayed_recordings``` list
* asset eventually plays and gets moved to ```nearby_played_recordings``` list
* listener leaves range of asset and asset is added to NEW list called ```in_between_recordings``` (need better name)
* listener re-enters asset's range and is NOT added back to ```nearby_unplayed_recordings``` list, because it is in ```in_between_recordings``` list 
* listener moves further than a pre-determined multiple distance (ie. 2x radius) from the asset's range and is removed from ```in_between_recordings``` list
* listener re-enters asset's range and is added back to ```nearby_unplayed_recordings``` list, making it available to be played again in the stream

**Comment by eosrei** [comment]
This was fixed with #185
