### ISSUE TITLE
add asset.loc_description to get_available_assets response

### ISSUE THREAD

**Issue by hburgund** [hburgund/roundware-server#50]
among other things, this would allow us to include any caption information available for a photo and stored in the description so that it could be displayed as an overlay.

this field clearly needs localization as the contained strings will often be displayed to the users.

**Comment by eosrei** [comment]
Tag.inject is sending tag and asset ids: https://github.com/hburgund/roundware-server/commit/f6a58418a5271b523068b06c2a9e6938f648232d#diff-457177168c88b69df85951524c0f3da2R153

Related to #135. May be able to be closed.

**Comment by hburgund** [comment]
it appears to already be in there.  I guess I made this change, but never updated the issue.  Perhaps I didn't close because localization was not done, but as you say, that's part of #135 so I will close this one now.
```
   "assets": [
        {
            "asset_id": 4134, 
            "asset_url": "/rwmedia/20131026-090418.wav", 
            "audio_length": 8266303855, 
            "description": "", 
            "language": "en", 
            "latitude": 37.77114, 
            "loc_description": "", 
            "longitude": -122.46836, 
            "mediatype": "audio", 
            "project": "FAM", 
            "submitted": false, 
            "tags": [
                {
                    "localized_value": "What do you first notice about this object or place?", 
                    "tag_category_name": "question", 
                    "tag_id": 157
                }, 
                {
                    "localized_value": "Museum", 
                    "tag_category_name": "usertype", 
                    "tag_id": 156
                }
            ]
        }, 
        ...
```
